### PR TITLE
setup telemetry and add account_connected event 

### PR DESCRIPTION
**Pull request by trilopin**
#### Summary
Based on https://github.com/mattermost/mattermost-plugin-servicenow/pull/177

Telemetry added while keeping min_server_version unchanged(6.3.0).

Added telemetry race prevention mechanisms and account_connected event after successful connect (it can be verified through logs or rudderstack-dev).

#### Ticket Link
FIxes https://mattermost.atlassian.net/browse/MM-51748

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann This PR is ready for your review

**Comment by hanzei** [comment]
@DHaussermann Gentle reminder to review this PR

**Comment by hanzei** [comment]
@DHaussermann Are we fine to merge the PR?

**Comment by DHaussermann** [comment]
Sorry for the delay @hanzei 

We never got to to a point where there was a good way to test telemetry tasks. As such we would typically merge tasks similar to this and differ testing.

I'm in favor of merging this task.

**Pull request merged**
