### PR TITLE
Fixed issue #143 and #160

### PR DESCRIPTION
**Pull request by manojmalik20**
#### Summary
- Fixed the styling of the Delete subscription menu item
- Fixed the styling of the menu options on old MM versions

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-servicenow/issues/143
https://github.com/mattermost/mattermost-plugin-servicenow/issues/160

### CODE REVIEW

**Comment by mickmister** [comment]
I'm not sure what I should be reviewing here. Should I review the changes that went into `mattermost-ui-library` that solves this issue?

**Comment by manojmalik20** [comment]
Sure @mickmister, here are the PRs - 
https://github.com/Brightscout/mm-ui-library/pull/58
https://github.com/Brightscout/mm-ui-library/pull/54

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
@manojmalik20 Would you please merge `master` into your PR?

**Review by AayushChaudhary0001 — CHANGES_REQUESTED** [review]
**The above PR has been tested for the following scenarios:-**
- **Fixed the styling of the delete subscription menu item**
 It was found working fine while testing and the delete button followed the desired styling as asked in the issue created.
- **Fixed the styling of the menu options in old MM versions**
 This issue was reported on MM v5.37.3. But since the minimum supported version of ServiceNow plugin is now 6.3.0. So, on testing this PR on 6.3.0, it was not working as expected. However, it was working fine for latest MM version.

Please look into this.
cc: @raghavaggarwal2308

**Comment by AayushChaudhary0001** [comment]
This PR has been tested for the above mentioned conditions, and are found working fine for every theme of Mattermost. Thus, approving this PR.

**Review by AayushChaudhary0001 — APPROVED** [review]

**Pull request merged**
